spring:
  h2:
    console:
      enabled: true
      path: '/h2-console'
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:~/bancoh2;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    password: ''
    plataform: h2
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop